[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]


[project]
name = "cellina"
version = "0.7.2"
description = "Cellina: Dual-encoder VAE for spatial transcriptomics with adversarial domain forgetting"
readme = "README.md"
requires-python = ">=3.10"
license = {file = "LICENSE"}
authors = [
    {name = "Abdul Moeed", email = "abdul.moeed@dkfz-heidelberg.de"},
    {name = "Daniel Dimitrov", email = "daniel.dimitrov@embl.de"},
]
maintainers = [
    {name = "Abdul Moeed", email = "abdul.moeed@dkfz-heidelberg.de"},
    {name = "Daniel Dimitrov", email = "daniel.dimitrov@embl.de"},
]
urls.Documentation = "https://github.com/PMBio/cellina"
urls.Source = "https://github.com/PMBio/cellina"
urls.Home-page = "https://github.com/PMBio/cellina"
dependencies = [
    "anndata",
    # for debug logging (referenced from the issue template)
    "session-info",
    "rich",
    "scvi-tools>=0.20.1",
    "torch",
]

[project.optional-dependencies]
dev = [
    # CLI for bumping the version number
    "bump2version",
    "pre-commit",
    "twine>=4.0.2"
]
doc = [
    "sphinx>=4",
    "sphinx-book-theme>=0.3.3",
    "myst-nb",
    "sphinxcontrib-bibtex>=1.0.0",
    "sphinx-autodoc-typehints",
    # For notebooks
    "ipykernel",
    "ipython",
    "sphinx-copybutton",
]
test = [
    "pytest",
    "pytest-cov",
]

[tool.coverage.run]
source = ["cellina"]
omit = [
    "**/test_*.py",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
xfail_strict = true
addopts = [
    "--import-mode=importlib",  # allow using test files with same name
]

[tool.isort]
include_trailing_comma = true
multi_line_output = 3
profile = "black"
skip_glob = ["docs/*"]

[tool.black]
line-length = 120
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''

[tool.jupytext]
formats = "ipynb,md"

[tool.cruft]
skip = [
    "tests",
    "src/**/__init__.py",
    "src/**/basic.py",
    "docs/api.md",
    "docs/changelog.md",
    "docs/references.bib",
    "docs/references.md",
    "docs/notebooks/example.ipynb"
]

[tool.hatch.build.targets.wheel]
packages = [
    "src/cellina"
]

[tool.hatch.build.targets.sdist]
include = [
    "src/cellina",
    "pyproject.toml",
    "README.md",
    "LICENSE",
]
